test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

google:
  service: GCS
  keyfile:
    {
      "type": "service_account",
      "project_id": "tmtre-20200922",
      "private_key_id": <%= Rails.application.credentials.gcp_storage[:private_key_id] %>,
      "private_key": <%= Rails.application.credentials.gcp_storage[:private_key].dump %>,
      "client_email": "croutons-active-storage@tmtre-20200922.iam.gserviceaccount.com",
      "client_id": "113506336071204424489",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/croutons-active-storage%40tmtre-20200922.iam.gserviceaccount.com",
    }
  project: "nel2112"
  bucket: "croutons-active-storage"
